// Generated by CoffeeScript 1.8.0
(function() {
  var app, application_root, bodyParser, collections, databaseURL, db, express, favicon, http, logger, server;

  application_root = __dirname;

  express = require("express");

  bodyParser = require('body-parser');

  logger = require('express-logger');

  http = require('http');

  databaseURL = "faodb";

  collections = ["seeds"];

  favicon = require('serve-favicon');

  db = require("mongojs").connect(databaseURL, collections);

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.use(favicon("images/favicon.png"));

  app.use(express["static"](__dirname));

  server = http.createServer(app);

  server.listen(app.get('port'), function() {
    return console.log("Express server listening on port " + (app.get('port')));
  });

}).call(this);
