// Generated by CoffeeScript 1.8.0
(function() {
  var app, app_root, bodyParser, express, favicon, http, logger, server;

  app_root = __dirname;

  express = require("express");

  bodyParser = require('body-parser');

  logger = require('express-logger');

  http = require('http');

  favicon = require('serve-favicon');

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.use(favicon("images/favicon.png"));

  app.use(express["static"](app_root));

  server = http.createServer(app);

  server.listen(app.get('port'), function() {
    return console.log("Express server listening on port " + (app.get('port')));
  });

}).call(this);
